spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/egovframework
    username: egov
    password: egov
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    show-sql: true

# sql query parameter binding (< Hibernate 6.1)
logging:
  level:
    org.hibernate.type.descriptor.sql: trace

# sql query parameter binding (>= Hibernate 6.1)
#logging:
#  level:
#    org.hibernate.orm.jdbc.bind: trace